# Generated by Django 3.2.10 on 2023-11-28 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_file_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='extension',
        ),
    ]
