# Generated by Django 3.2.10 on 2023-11-28 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 28, 5, 42, 5, 816733, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 11, 28, 5, 42, 5, 816707, tzinfo=utc), null=True),
        ),
    ]
